name: Download Burpsuite Professtional

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Download burpsuite pro
      - name: download
        run: |
          wget "https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar" -O burpsuite_pro.jar
      
  
      # Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release latest
          draft: false
          prerelease: false

      - name: release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          file: ./burpsuite_pro.jar
          asset_name: burpsuite_pro.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "test"
          
