name: Download Burpsuite Professtional

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          repo: x-hi/x-hi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # Download burpsuite pro
      - name: download
        run: |
          wget "https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar" -O burpsuite_pro.jar
      
      # Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release BurpSuite
          draft: false
          prerelease: false

      - name: release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./burpsuite_pro.jar
          asset_name: burpsuite_pro.jar
          asset_content_type: application/x-jar
          
