name: Download Burpsuite Professtional

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Download burpsuite pro
      - run: wget https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar -O burpsuite_pro.jar
      
      # Delete old releases
      - uses: dev-drprasad/delete-older-releases@v0.2
        with:
          keep_latest: false
          delete_tags: true
  
      # Release
      - name: create release tag
        id: tag
        run: |
          echo "::set-output name=release::Burpsuite_Pro_$(date +"%Y.%m.%d")"
      - name: release
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{ steps.tag.outputs.release }}
          files: |
            ./burpsuite_pro.jar
