name: Download Burpsuite Professtional

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Download burpsuite pro
      - name: download
        run: |
          wget "https://portswigger-cdn.net/burp/releases/download?product=pro&type=Jar" -O burpsuite_pro.jar
      
  
      # Release
      - name: create release tag
        id: tag
        run: |
          echo "::set-output name=release::Burpsuite_Pro_$(date +"%Y.%m.%d")"

      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./burpsuite_pro.jar
          asset_name: burpsuite_pro.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
          
